spring:
  application:
    name: demo
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true   
server:
  port: 8080

# OpenAPI (Springdoc) 配置
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  packages-to-scan: com.example.demo.controller

# 可選：自定義 OpenAPI 信息
openapi:
  info:
    title: Demo API
    version: 1.0.0
    description: API documentation for Demo project